Use the ES6 import method to import module
YuZhangYuanYYZ/todoListAPI pull request #1
Opened 2021-07-05 13:01 UTC by YuZhangYuanYYZ

2021-07-06 10:13 UTC, lanmengyujing commented on todoListAPI.js
> +  todos = newTodos;
this can be deleted now.

2021-07-06 10:13 UTC, lanmengyujing commented on todoListAPI.js
> +  res.send({}) ;
does this follow RESTful API response format?

2021-07-06 10:14 UTC, lanmengyujing commented on todoListAPI.js
> +    res.send(resTodo);
this PUT method also do not follow RESTfull pattern

2021-07-06 10:15 UTC, lanmengyujing commented on todoData.js
> +export let todos =[{"content":"hello zero","id":0},{"content":"hello one","id":1},{"content":"hello two","id":2},{"content":"hello three","id":3}];
where is the Store you have created?

2021-07-06 10:16 UTC, lanmengyujing requested changes
it is better to have a store to handle the update, delete, add, query for todos.
```
TodoStore {
addTodo()
deleteTodo()
updateTodo()
createTodo()
}
```

2021-07-06 12:55 UTC, jingliu-rea commented on todoListAPI.js
> +  res.send({}) ;
empty does not mean {}

2021-07-06 12:56 UTC, jingliu-rea commented on todoListAPI.js
> +    res.send(resTodo);
resTodo is a list of todo, not a single object

2021-07-06 13:25 UTC, jingliu-rea commented on todoListAPI.js
> +  res.send({}) ;
res.status(200).send()

2021-07-06 13:26 UTC, lanmengyujing commented on todoListAPI.js
> +  res.send({}) ;
empty does not mean {}
```
res.status(200).send()
```

2021-07-06 13:26 UTC, lanmengyujing commented on todoListAPI.js
> +    res.send(resTodo);
resTodo is a list of todo, not a single object

2021-07-10 02:46 UTC, YuZhangYuanYYZ commented on todoListAPI.js
> +  todos = newTodos;
ok.thank for your reminding.

2021-07-10 02:51 UTC, YuZhangYuanYYZ commented on todoListAPI.js
> +  res.send({}) ;
yeah,you're right.

2021-07-10 03:11 UTC, YuZhangYuanYYZ commented on todoListAPI.js
> +    res.send(resTodo);
???resTodo is a single object.

2021-07-10 03:15 UTC, merged